apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
  # IMPORTANT: The ServiceAccount remains in the namespace where your runner is deployed.
  namespace: actions-runner-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: github-runner-sa
  # This must match the namespace of your ServiceAccount.
  namespace: actions-runner-system
roleRef:
  kind: ClusterRole
  name: github-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io