#!/usr/bin/env bash
set -euo pipefail
export DOCKER_API_VERSION=1.43
# Base tools for Oh My Zsh and kind
sudo apt-get update
sudo apt-get install -y --no-install-recommends zsh git curl wget ca-certificates

# Oh My Zsh (unattended)
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Powerlevel10k theme for Oh My Zsh
if [ ! -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
  echo "Installing Powerlevel10k theme..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
  
  # Set theme in .zshrc
  if [ -f "$HOME/.zshrc" ]; then
    sed -i 's/^ZSH_THEME=.*/ZSH_THEME="powerlevel10k\/powerlevel10k"/' "$HOME/.zshrc"
  fi
  
  # Create a default p10k config to skip the configuration wizard
  # This uses the "lean" style with 8 colors, unicode, and transient prompt
  if [ ! -f "$HOME/.p10k.zsh" ]; then
    cat > "$HOME/.p10k.zsh" <<'P10K_EOF'
# Generated by Powerlevel10k configuration wizard on $(date)
# Based on the "lean" style with sensible defaults for development containers

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  autoload -Uz is-at-least && is-at-least 5.1 || return

  # Prompt style: lean
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=none

  # Basic style
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=

  # Prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    dir
    vcs
    newline
    prompt_char
  )
  
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    direnv
    asdf
    virtualenv
    anaconda
    pyenv
    goenv
    nodenv
    nvm
    nodeenv
    rbenv
    rvm
    fvm
    luaenv
    jenv
    plenv
    perlbrew
    phpenv
    scalaenv
    haskell_stack
    kubecontext
    terraform
    aws
    aws_eb_env
    azure
    gcloud
    google_app_cred
    toolbox
    context
    nordvpn
    ranger
    nnn
    lf
    xplr
    vim_shell
    midnight_commander
    nix_shell
    chezmoi_shell
    time
  )

  # Segment colors
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_VCS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196

  # Git settings
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'

  # Kubernetes context
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kustomize'
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=134

  # Transient prompt (clean up previous prompts)
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  # Instant prompt mode
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false
}

# Restore options.
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
P10K_EOF
  fi
  
  # Source p10k config in .zshrc if not already done
  if [ -f "$HOME/.zshrc" ] && ! grep -q "source ~/.p10k.zsh" "$HOME/.zshrc"; then
    echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> "$HOME/.zshrc"
  fi
  
  echo "Powerlevel10k installed! Note: For best experience, install 'MesloLGS NF' font on your local machine."
  echo "Download from: https://github.com/romkatv/powerlevel10k#manual-font-installation"
fi

# kind (latest release)
if ! command -v kind >/dev/null 2>&1; then
  curl -fsSL https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64 -o /tmp/kind
  chmod +x /tmp/kind
  sudo mv /tmp/kind /usr/local/bin/kind
fi

# kubectl (latest stable)
if ! command -v kubectl >/dev/null 2>&1; then
  KUBECTL_VERSION="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
  curl -fsSL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o /tmp/kubectl
  chmod +x /tmp/kubectl
  sudo mv /tmp/kubectl /usr/local/bin/kubectl
fi

# helm (latest stable)
if ! command -v helm >/dev/null 2>&1; then
  curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
fi

# Add kubectl alias to zsh config
if [ -f "$HOME/.zshrc" ] && ! grep -q "^alias k='kubectl'$" "$HOME/.zshrc"; then
  echo "alias k='kubectl'" >> "$HOME/.zshrc"
fi

# Enable kubectl autocompletion for zsh (including alias k)
if [ -f "$HOME/.zshrc" ] && ! grep -q "kubectl completion zsh" "$HOME/.zshrc"; then
  cat >> "$HOME/.zshrc" <<'EOF'
source <(kubectl completion zsh)
compdef __start_kubectl k
EOF
fi

# Create a default kind cluster if Docker is available and no cluster exists
if command -v docker >/dev/null 2>&1; then
  if ! kind get clusters >/dev/null 2>&1 || ! kind get clusters | grep -q '^kind$'; then
    kind create cluster --config kind/kind-config.yaml
  fi
fi

##########################
#### Traefik Setup #######
##########################
echo "------------------------"
echo "[INFO] Setting up Traefik Ingress Controller..."
echo "------------------------"

helm repo add traefik https://traefik.github.io/charts
helm repo update
helm install traefik traefik/traefik \
  --create-namespace --namespace traefik \
  -f traefik/values.yaml

echo "------------------------"
echo "[INFO] Finish Traefik Setup..."
echo "------------------------"

##########################
#### ARGOCD Setup ########
##########################
echo "------------------------"
echo "[INFO] Setting up Argo CD..."
echo "------------------------"

helm repo add argo https://argoproj.github.io/argo-helm
helm repo update
helm upgrade argocd argo/argo-cd --version 9.2.3 --install --create-namespace -n argocd -f argocd/values.yaml

echo "------------------------"
echo "[INFO] Finish Argo CD Setup..."
echo "------------------------"

###################################
### Metric Server SETUP ###########
###################################
echo "------------------------"
echo "[INFO] Setting up Metric Server..."
echo "------------------------"

helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
helm install metrics-server metrics-server/metrics-server --version 3.13.0 \
-f metrics-server/values.yaml \
-n kube-system

echo "------------------------"
echo "[INFO] Finishing Metric Server setup..."
echo "------------------------"